version: '3'

networks:
  MUStoreNet:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - 8080:80
    volumes:
      - ./MUStore:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - mysql
      - php
    networks:
      - MUStoreNet

  mysql:
    image: mysql:5.7.22
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: mu_store
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - MUStoreNet

  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./MUStore:/var/www/html
    ports:
      - 9000:9000
    networks:
      - MUStoreNet